name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    name: Build release distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build release distributions
        run: uv build  # uv's built-in build command

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-distributions
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: [release-build]
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
    
    environment:
      name: pypi
      url: https://pypi.org/p/tdoc

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: release-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
